version: '3.7'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      # - ./src/app.js:/backend/src/app.js
      - ./src:/backend/src
    ports:
      - 3000:3000
  database:
    image: mongo:5
    ports:
      - 27017:27017